language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/shoe_api_db

node_js:  
  - "8.9.4"

before_script:
  - psql -c 'create database  shoe_api_db;' -U postgres
  - psql -U postgres -d shoe_api_db -a -f sql/tables.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2